### ISSUE TITLE
ImportError: No module named google.protobuf.internal

### ISSUE THREAD

**Issue by AnyPython** [yahoo/open_nsfw#14]
run 'sudo docker run --volume=$(pwd):/workspace caffe:cpu python classify_nsfw.py --model_def nsfw_model/deploy.prototxt --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel 1.png
'
and it returns me:
libdc1394 error: Failed to initialize libdc1394
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "classify_nsfw.py", line 16, in <module>
    import caffe
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/opt/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/opt/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/opt/caffe/python/caffe/proto/caffe_pb2.py", line 4, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

**Comment by AnyPython** [comment]
And when i run 'sudo docker run caffe:cpu caffe --version', it shows 
'
libdc1394 error: Failed to initialize libdc1394
caffe version 1.0.0-rc3
'

**Comment by XuefeiWen** [comment]
I've got the same problem when I tried installing caffe. I solved it by reinstall: 
sudo pip install protobuf
Reference link: https://groups.google.com/forum/#!topic/caffe-users/9Q10WkpCGxs
The another error: libdc1394 error: Failed to initialize libdc1394. I solved it by: 
sudo ln /dev/null /dev/raw1394
Reference link: http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394/12689392#12689392

**Comment by AnyPython** [comment]
Thank you, XuefeiWen. Before i opened this issue, i had tried some ways like you advice, but it didn't work. I guess it occurred because of my computer, i will try again on another machine. Thanks a lot.

**Comment by dragey** [comment]
I hit "libdc1394 error" too, and "sudo ln /dev/null /dev/raw1394" did not work in my two ubantu sytems (both of them were inited from VM) .... Is this a fatal issue? I can see it did not block follwoing process.

**Comment by MetaAshley** [comment]
This is an automatically generated message.

awolf@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by ZhaoQiang2015** [comment]
I have meet the similar question.when I input the commond:docker run --volume=$(pwd):/workspace caffe:cpu python ./classify_nsfw.py --model_def nsfw_model/deploy.prototxt --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel test_image.jpg
it failed with the output:
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "./classify_nsfw.py", line 16, in <module>
    import caffe
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/opt/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/opt/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
ImportError: No module named skimage.io
Who knows how solve it? I would very greatful to you.

**Comment by AnyPython** [comment]
I have tested in another computer with ubuntu system which is not inited from VM, it still has the same problem("libdc1394 error"). So i guess it's none of the VM's business. And i ignore the notice and  try running "sudo docker run --volume=$(pwd):/workspace caffe:cpu python classify_nsfw.py --model_def nsfw_model/deploy.prototxt --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel 1.png", it works! And you could ignore that problem, too. If you hit "ImportError", please test it with ubuntu system which is not inited from VM. @XuefeiW @willswl @ZhaoQiang2015
